import { useState, useEffect, useCallback } from "react";
import "./ClearcheckPanel.css";

type AuditRow = {
  id: string;
  source: string;
  file_name: string;
  status: "clear" | "flagged";
  labels: { name: string; confidence: number }[];
  moderation_flags: string[];
  image_file_url: string | null;
  report_file_url: string | null;
  created_at: string;
};

type Props = {
  onClose?: () => void;
  refreshKey?: number;
};

export function AuditLogPanel({ onClose, refreshKey }: Props) {
  const [audits, setAudits] = useState<AuditRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [filter, setFilter] = useState<"all" | "clear" | "flagged">("all");

  const fetchAudits = useCallback(async () => {
    setFetchError(null);
    try {
      const resp = await fetch("/api/clearcheck/audits", { credentials: "include" });
      if (resp.ok) {
        const data = await resp.json();
        setAudits(data.audits || []);
      } else if (resp.status === 401) {
        setFetchError("Sign in to view audit logs");
      } else {
        setFetchError("Failed to load audit log");
      }
    } catch {
      setFetchError("Network error — could not load audit log");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchAudits();
  }, [fetchAudits, refreshKey]);

  const toggleExpand = (id: string) =>
    setExpandedId((prev) => (prev === id ? null : id));

  const downloadOne = useCallback((audit: AuditRow) => {
    if (audit.report_file_url) {
      const a = document.createElement("a");
      a.href = `/api/clearcheck/audits/${audit.id}/download`;
      a.download = `clearcheck-report.zip`;
      a.click();
    }
  }, []);

  const downloadAll = useCallback(() => {
    if (audits.length === 0) return;
    const lines: string[] = [
      "# Clearcheck — Full Audit Log",
      "",
      `**Exported:** ${new Date().toLocaleString()}`,
      `**Total Audits:** ${audits.length}`,
      "",
      "---",
      "",
    ];

    for (const a of audits) {
      lines.push(
        `## ${a.file_name}`,
        "",
        `- **Date:** ${new Date(a.created_at).toLocaleString()}`,
        `- **Source:** ${a.source}`,
        `- **Status:** ${a.status === "clear" ? "CLEAR" : "FLAGGED"}`,
        "",
        "### Labels",
        "",
        ...a.labels.map((l) => `- ${l.name}: ${l.confidence.toFixed(1)}%`),
        "",
      );
      if (a.moderation_flags.length > 0) {
        lines.push(
          "### Moderation Flags",
          "",
          ...a.moderation_flags.map((f) => `- ${f}`),
          "",
        );
      }
      lines.push("---", "");
    }

    lines.push("*Generated by Clearcheck*");

    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `clearcheck-audit-log-${Date.now()}.md`;
    anchor.click();
    URL.revokeObjectURL(url);
  }, [audits]);

  const clearCount = audits.filter((a) => a.status === "clear").length;
  const flaggedCount = audits.filter((a) => a.status === "flagged").length;
  const filtered = filter === "all" ? audits : audits.filter((a) => a.status === filter);

  return (
    <div className="audit-page">
      <div className="audit-page-content">
        <div className="audit-page-header">
          <div>
            <h1 className="audit-page-title">Audit Log</h1>
            <p className="audit-page-subtitle">
              {audits.length} audit{audits.length !== 1 ? "s" : ""} &middot; {clearCount} clear &middot; {flaggedCount} flagged
            </p>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <button
              type="button"
              className={`audit-download-all-btn ${audits.length === 0 ? "audit-download-all-btn--disabled" : ""}`}
              onClick={downloadAll}
              disabled={audits.length === 0}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
              Download All
            </button>
            {onClose && (
              <button
                type="button"
                className="audit-close-btn"
                onClick={onClose}
                title="Close"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <line x1="18" y1="6" x2="6" y2="18" />
                  <line x1="6" y1="6" x2="18" y2="18" />
                </svg>
              </button>
            )}
          </div>
        </div>

        <div className="audit-filter-row">
          {(["all", "clear", "flagged"] as const).map((f) => (
            <button
              key={f}
              type="button"
              className={`audit-filter-btn ${filter === f ? "audit-filter-btn--active" : ""}`}
              onClick={() => setFilter(f)}
            >
              {f === "all" ? "All" : f === "clear" ? "Clear" : "Flagged"}
              <span className="audit-filter-count">
                {f === "all" ? audits.length : f === "clear" ? clearCount : flaggedCount}
              </span>
            </button>
          ))}
        </div>

        {fetchError ? (
          <div className="audit-empty">
            <span style={{ color: "#ef4444" }}>{fetchError}</span>
          </div>
        ) : loading ? (
          <div className="audit-empty">
            <span>Loading audit log...</span>
          </div>
        ) : filtered.length === 0 ? (
          <div className="audit-empty">
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
              <rect x="8" y="2" width="8" height="4" rx="1" />
            </svg>
            <span>No audits match this filter.</span>
          </div>
        ) : (
          <div className="audit-table">
            <div className="audit-table-head">
              <span className="audit-col audit-col--file">File</span>
              <span className="audit-col audit-col--source">Source</span>
              <span className="audit-col audit-col--status">Status</span>
              <span className="audit-col audit-col--labels">Top Labels</span>
              <span className="audit-col audit-col--date">Date</span>
              <span className="audit-col audit-col--action" />
            </div>
            {filtered.map((audit) => {
              const isOpen = expandedId === audit.id;
              return (
                <div key={audit.id} className={`audit-row-wrap ${isOpen ? "audit-row-wrap--open" : ""}`}>
                  <div className="audit-row" onClick={() => toggleExpand(audit.id)}>
                    <span className="audit-col audit-col--file">
                      <div className="audit-row-thumb">
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2" /><circle cx="8.5" cy="8.5" r="1.5" /><polyline points="21 15 16 10 5 21" /></svg>
                      </div>
                      <span className="audit-row-filename">{audit.file_name}</span>
                    </span>
                    <span className="audit-col audit-col--source">
                      <span className="audit-source-tag">{audit.source === "upload" ? "Upload" : "Canvas"}</span>
                    </span>
                    <span className="audit-col audit-col--status">
                      <span className={`cc-status-badge cc-status-badge--${audit.status}`}>
                        {audit.status === "clear" ? "Clear" : "Flagged"}
                      </span>
                    </span>
                    <span className="audit-col audit-col--labels">
                      <span className="audit-labels-preview">
                        {audit.labels.slice(0, 3).map((l) => l.name).join(", ")}
                        {audit.labels.length > 3 && ` +${audit.labels.length - 3}`}
                      </span>
                    </span>
                    <span className="audit-col audit-col--date">
                      {new Date(audit.created_at).toLocaleDateString()}
                    </span>
                    <span className="audit-col audit-col--action" onClick={(e) => e.stopPropagation()}>
                      <button
                        type="button"
                        className="audit-download-one-btn"
                        onClick={() => downloadOne(audit)}
                        title="Download report"
                        disabled={!audit.report_file_url}
                      >
                        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
                      </button>
                      <svg
                        className={`audit-row-chevron ${isOpen ? "audit-row-chevron--open" : ""}`}
                        width="12"
                        height="12"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.5"
                      >
                        <polyline points="6 9 12 15 18 9" />
                      </svg>
                    </span>
                  </div>
                  {isOpen && (
                    <div className="audit-row-detail">
                      {audit.moderation_flags.length > 0 && (
                        <div className="audit-row-flags">
                          {audit.moderation_flags.map((f, i) => (
                            <div key={i} className="cc-flag-item">
                              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" /><line x1="12" y1="9" x2="12" y2="13" /><line x1="12" y1="17" x2="12.01" y2="17" /></svg>
                              <span>{f}</span>
                            </div>
                          ))}
                        </div>
                      )}
                      <div className="audit-row-label-grid">
                        {audit.labels.map((l, i) => (
                          <div key={i} className="audit-row-label-item">
                            <span className="audit-row-label-name">{l.name}</span>
                            <div className="cc-confidence-bar">
                              <div className="cc-confidence-fill" style={{ width: `${l.confidence}%` }} />
                            </div>
                            <span className="cc-confidence-value">{l.confidence.toFixed(1)}%</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
